apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellok8s-pod
  template:
    metadata:
      labels:
        app: hellok8s-pod
    spec:
      containers:
        - image: jianjustin/hellok8s:v1
          name: hellok8s-container