version: '3.8'

services:
  web2:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
       - type: bind
         source: ./nginx.conf
         target: /etc/nginx/nginx.conf
    ports:
      - "9083:80/tcp"
    environment:
      - NGINX_PORT=80