version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - app-tier
    ports:
      - 3306:3306